language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.7"
  # - "3.5"
  # - "3.6"
install:
  - pip install numpy ipython coverage pytest pytest-cov numba astropy==2.0.16 astromodels
  - python setup.py install
env:
  NUMBA_DISABLE_JIT=1

script:
  - python -m pytest -vv --cov=pynchrotron/
  - codecov --token=95a59626-4d5a-47a2-9263-4fa3a919a1bd
